### ISSUE TITLE
Allow customization of the prefix only.

### ISSUE THREAD

**Issue by byteveil** [tailer-dev/LuckyTPA#2]
Instead of changing every response message, there can be a configuration entry or two saying whether it's enabled and what the prefix is in chat.

```yml
prefix:
  enabled: true
  text: "&f[&aLuckyTPA&f] &7"
```
